<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>assert.doesNotThrow(fn[, error][, message]) | Node.js API 文档</title>
  <link rel="icon" sizes="32x32" type="image/png" href="http://static.nodejs.cn/_static/img/favicon.png"><link rel="stylesheet" href="/api/api.css">
  <script>
    document.write('<link href="http://nodejs.cn/api/assert/'&#32;+&#32;(location.port?'':'//static.nodejs.cn')&#32;+&#32;'/_static/css/api.css?1576756292559" rel="stylesheet">')
  </script>
</head>
<body class="alt apidoc" id="page_api_item">
  <div id="api-section-assert">
    <div id="content" class="clearfix">
  
      <div id="column1" data-id="__ID__" class="interior">
        <header>
          <h1>assert.doesNotThrow(fn[, error][, message])</h1>
          <div id="gtoc">
            <ul>
              <li>v12.14.0</li>
              <li>
                <a href="../assert.html#assert_assert_doesnotthrow_fn_error_message" name="toc">返回上层文档</a>
              </li>
              <li>
                <a href="https://github.com/nodejscn/node-api-cn/edit/master/assert/assert_doesnotthrow_fn_error_message.md" rel="nofollow" target="_blank">提交修改</a>
              </li>
              <li>
                <a href="http://nodejs.cn/search" name="toc">搜索</a>
              </li>
            </ul>
          </div>
          <hr>
        </header>

        <div id="biz_item"></div>
  
        <div id="apicontent">
          <div id="content_left"><div class="api_metadata">
<details class="changelog"><summary>&#x7248;&#x672C;&#x5386;&#x53F2;</summary>
<table>
<tbody><tr><th>&#x7248;&#x672C;</th><th>&#x53D8;&#x66F4;</th></tr>
<tr><td>v5.11.0, v4.4.5</td>
<td><p>The <code>message</code> parameter is respected now.</p></td></tr>
<tr><td>v4.2.0</td>
<td><p>The <code>error</code> parameter can now be an arrow function.</p></td></tr>
<tr><td>v0.1.21</td>
<td><p><span>&#x65B0;&#x589E;&#x4E8E;: v0.1.21</span></p></td></tr>
</tbody></table>
</details>
</div><ul>
<li><code>fn</code> <a href="http://nodejs.cn/s/ceTQa6" target="_blank" rel="nofollow" class="type">&lt;Function&gt;</a></li>
<li><code>error</code> <a href="http://nodejs.cn/s/G38byW" target="_blank" rel="nofollow" class="type">&lt;RegExp&gt;</a> | <a href="http://nodejs.cn/s/ceTQa6" target="_blank" rel="nofollow" class="type">&lt;Function&gt;</a></li>
<li><code>message</code> <a href="http://nodejs.cn/s/9Tw2bK" target="_blank" rel="nofollow" class="type">&lt;string&gt;</a></li>
</ul><p>&#x65AD;&#x8A00; <code>fn</code> &#x51FD;&#x6570;&#x4E0D;&#x4F1A;&#x629B;&#x51FA;&#x9519;&#x8BEF;&#x3002;</p><p>&#x4F7F;&#x7528; <code>assert.doesNotThrow()</code> &#x5B9E;&#x9645;&#x4E0A;&#x6CA1;&#x6709;&#x7528;&#x5904;&#xFF0C;&#x56E0;&#x4E3A;&#x6355;&#x83B7;&#x9519;&#x8BEF;&#x7136;&#x540E;&#x91CD;&#x65B0;&#x629B;&#x51FA;&#x5B83;&#x6CA1;&#x6709;&#x4EFB;&#x4F55;&#x597D;&#x5904;&#x3002;
&#x5E94;&#x8BE5;&#x8003;&#x8651;&#x5728;&#x4E0D;&#x5E94;&#x629B;&#x51FA;&#x9519;&#x8BEF;&#x7684;&#x7279;&#x5B9A;&#x4EE3;&#x7801;&#x8DEF;&#x5F84;&#x65C1;&#x8FB9;&#x6DFB;&#x52A0;&#x6CE8;&#x91CA;&#xFF0C;&#x5E76;&#x5C3D;&#x53EF;&#x80FD;&#x4FDD;&#x7559;&#x9519;&#x8BEF;&#x6D88;&#x606F;&#x3002;</p><p>&#x5F53;&#x8C03;&#x7528; <code>assert.doesNotThrow()</code> &#x65F6;&#xFF0C;&#x5B83;&#x5C06;&#x7ACB;&#x5373;&#x8C03;&#x7528; <code>fn</code> &#x51FD;&#x6570;&#x3002;</p><p>&#x5982;&#x679C;&#x629B;&#x51FA;&#x9519;&#x8BEF;&#x5E76;&#x4E14;&#x5B83;&#x4E0E; <code>error</code> &#x53C2;&#x6570;&#x6307;&#x5B9A;&#x7684;&#x7C7B;&#x578B;&#x76F8;&#x540C;&#xFF0C;&#x5219;&#x629B;&#x51FA; <code>AssertionError</code>&#x3002;
&#x5982;&#x679C;&#x9519;&#x8BEF;&#x7684;&#x7C7B;&#x578B;&#x4E0D;&#x540C;&#xFF0C;&#x6216;&#x8005; <code>error</code> &#x53C2;&#x6570;&#x672A;&#x5B9A;&#x4E49;&#xFF0C;&#x5219;&#x9519;&#x8BEF;&#x5C06;&#x4F20;&#x64AD;&#x56DE;&#x8C03;&#x7528;&#x65B9;&#x3002;</p><p>&#x5982;&#x679C;&#x6307;&#x5B9A;&#xFF0C;&#x5219; <code>error</code> &#x53EF;&#x4EE5;&#x662F; <a href="http://nodejs.cn/s/5wDLcp" rel="nofollow"><code>Class</code></a>&#x3001;<a href="http://nodejs.cn/s/tbQJCP" rel="nofollow"><code>RegExp</code></a> &#x6216;&#x9A8C;&#x8BC1;&#x51FD;&#x6570;&#x3002;
&#x6709;&#x5173;&#x66F4;&#x591A;&#x8BE6;&#x7EC6;&#x4FE1;&#x606F;&#xFF0C;&#x8BF7;&#x53C2;&#x89C1; <a href="http://nodejs.cn/s/sGRMSp" rel="nofollow"><code>assert.throws()</code></a>&#x3002;</p><p>&#x4F8B;&#x5982;&#xFF0C;&#x4EE5;&#x4E0B;&#x793A;&#x4F8B;&#x5C06;&#x629B;&#x51FA; <a href="http://nodejs.cn/s/Z7Lqyj" rel="nofollow"><code>TypeError</code></a>&#xFF0C;&#x56E0;&#x4E3A;&#x65AD;&#x8A00;&#x4E2D;&#x6CA1;&#x6709;&#x5339;&#x914D;&#x7684;&#x9519;&#x8BEF;&#x7C7B;&#x578B;&#xFF1A;</p><pre><code class="language-js">assert.doesNotThrow(
  () =&gt; {
    throw new TypeError(&apos;&#x9519;&#x8BEF;&#x503C;&apos;);
  },
  SyntaxError
);
</code></pre><p>&#x4EE5;&#x4E0B;&#x793A;&#x4F8B;&#x5C06;&#x5BFC;&#x81F4; <code>AssertionError</code>&#xFF0C;&#x5E76;&#x663E;&#x793A;&#x6D88;&#x606F; &apos;Got unwanted exception...&apos;&#xFF1A;</p><pre><code class="language-js">assert.doesNotThrow(
  () =&gt; {
    throw new TypeError(&apos;&#x9519;&#x8BEF;&#x503C;&apos;);
  },
  TypeError
);
</code></pre><p>&#x5982;&#x679C;&#x629B;&#x51FA; <code>AssertionError</code> &#x5E76;&#x4E3A; <code>message</code> &#x53C2;&#x6570;&#x63D0;&#x4F9B;&#x4E86;&#x503C;&#xFF0C;&#x5219; <code>message</code> &#x7684;&#x503C;&#x5C06;&#x9644;&#x52A0;&#x5230; <code>AssertionError</code> &#x6D88;&#x606F;&#xFF1A;</p><pre><code class="language-js">assert.doesNotThrow(
  () =&gt; {
    throw new TypeError(&apos;&#x9519;&#x8BEF;&#x503C;&apos;);
  },
  /&#x9519;&#x8BEF;&#x503C;/,
  &apos;&#x51FA;&#x9519;&#x5566;&apos;
);
// AssertionError: Got unwanted exception: &#x51FA;&#x9519;&#x5566;
</code></pre></div>
          <div id="content_right"><div class="api_metadata">
<details class="changelog"><summary>History</summary>
<table>
<tbody><tr><th>Version</th><th>Changes</th></tr>
<tr><td>v5.11.0, v4.4.5</td>
<td><p>The <code>message</code> parameter is respected now.</p></td></tr>
<tr><td>v4.2.0</td>
<td><p>The <code>error</code> parameter can now be an arrow function.</p></td></tr>
<tr><td>v0.1.21</td>
<td><p><span>Added in: v0.1.21</span></p></td></tr>
</tbody></table>
</details>
</div><ul>
<li><code>fn</code> <a href="http://nodejs.cn/s/ceTQa6" target="_blank" rel="nofollow" class="type">&lt;Function&gt;</a></li>
<li><code>error</code> <a href="http://nodejs.cn/s/G38byW" target="_blank" rel="nofollow" class="type">&lt;RegExp&gt;</a> | <a href="http://nodejs.cn/s/ceTQa6" target="_blank" rel="nofollow" class="type">&lt;Function&gt;</a></li>
<li><code>message</code> <a href="http://nodejs.cn/s/9Tw2bK" target="_blank" rel="nofollow" class="type">&lt;string&gt;</a></li>
</ul><p>Asserts that the function <code>fn</code> does not throw an error.</p><p>Using <code>assert.doesNotThrow()</code> is actually not useful because there
is no benefit in catching an error and then rethrowing it. Instead, consider
adding a comment next to the specific code path that should not throw and keep
error messages as expressive as possible.</p><p>When <code>assert.doesNotThrow()</code> is called, it will immediately call the <code>fn</code>
function.</p><p>If an error is thrown and it is the same type as that specified by the <code>error</code>
parameter, then an <code>AssertionError</code> is thrown. If the error is of a different
type, or if the <code>error</code> parameter is undefined, the error is propagated back
to the caller.</p><p>If specified, <code>error</code> can be a <a href="http://nodejs.cn/s/5wDLcp" rel="nofollow"><code>Class</code></a>, <a href="http://nodejs.cn/s/tbQJCP" rel="nofollow"><code>RegExp</code></a> or a validation
function. See <a href="http://nodejs.cn/s/sGRMSp" rel="nofollow"><code>assert.throws()</code></a> for more details.</p><p>The following, for instance, will throw the <a href="http://nodejs.cn/s/Z7Lqyj" rel="nofollow"><code>TypeError</code></a> because there is no
matching error type in the assertion:</p><pre><code class="language-js">assert.doesNotThrow(
  () =&gt; {
    throw new TypeError(&apos;Wrong value&apos;);
  },
  SyntaxError
);
</code></pre><p>However, the following will result in an <code>AssertionError</code> with the message
&apos;Got unwanted exception...&apos;:</p><pre><code class="language-js">assert.doesNotThrow(
  () =&gt; {
    throw new TypeError(&apos;Wrong value&apos;);
  },
  TypeError
);
</code></pre><p>If an <code>AssertionError</code> is thrown and a value is provided for the <code>message</code>
parameter, the value of <code>message</code> will be appended to the <code>AssertionError</code>
message:</p><pre><code class="language-js">assert.doesNotThrow(
  () =&gt; {
    throw new TypeError(&apos;Wrong value&apos;);
  },
  /Wrong value/,
  &apos;Whoops&apos;
);
// Throws: AssertionError: Got unwanted exception: Whoops
</code></pre></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
  <script>
    document.write('<script src="http://nodejs.cn/api/assert/'&#32;+&#32;(location.port&#32;?&#32;''&#32;:&#32;'//static.nodejs.cn')&#32;+&#32;'/_static/js/api.js?1576756292559"><\/script>');
  </script>
</body>
</html>